from django.db import models

# Create your models here.
GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)

BLOOD = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
)

MARITAL = (
    ('Single', 'Single'),
    ('Married', 'Married')
)

LANGUAGE = (
    ('Hindi', 'Hindi'),
    ('English', 'English'),
    ('Bengali', 'Bengali'),
    ('Telugu', 'Telugu'),
    ('Marathi', 'Marathi'),
    ('Tamil', 'Tamil'),
    ('Gujarati', 'Gujarati'),
    ('Kannada', 'Kannada'),
    ('Malayalam', 'Malayalam'),
    ('Odia', 'Odia'),
    ('Punjabi', 'Punjabi')
)

SPECIALIZATION = (
    ('Accountancy', 'Accountancy'),
    ('AGRICULTURE', 'Agriculture'),
    ('Arabic', 'Arabic'),
    ('Arts', 'Arts'),
    ('Auditing', 'Auditing'),
    ('B. Pharmacy', 'B. Pharmacy'),
    ('Bio Tech', 'Bio Tech'),
    ('Business', 'Business'),
    ('Business economics', 'Business economics'),
    ('Business finance', 'Business finance'),
    ('Chemical', 'Chemical'),
    ('Chemistry', 'Chemistry'),
    ('Civil Engineering', 'Civil Engineering'),
    ('Commerce', 'Commerce'),
    ('Commercial ART7 ADVERTISING, PHOTOGRAPHY MASS COMM.', 'Commercial ART7 ADVERTISING, PHOTOGRAPHY MASS COMM.'),
    ('Computer', 'Computer'),
    ('Computer Application', 'Computer Application'),
    ('Computer Engineering', 'Computer Engineering'),
    ('Computer Science & ENGG', 'Computer Science & ENGG'),
    ('COMPUTER SCIENCE AND ENGENEERING', 'COMPUTER SCIENCE AND ENGENEERING'),
    ('Computers', 'Computers'),
    ('Cost accounting', 'Cost accounting'),
    ('Dental Surgen', 'Dental Surgen'),
    ('DIPLOMA', 'DIPLOMA'),
    ('Economics', 'Economics'),
    ('Electrical', 'Electrical'),
    ('Electrical and Electronic Engineering', 'Electrical and Electronic Engineering'),
    ('ELECTRONIC & COMMUNICATIONS', 'ELECTRONIC & COMMUNICATIONS'),
    ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'),
    ('Electronics * Instrumentation Engineering', 'Electronics * Instrumentation Engineering'),
    ('Electronics Engineering', 'Electronics Engineering'),
    ('Fashion Designe & Garment Technology', 'Fashion Designe & Garment Technology'),
    ('Finance', 'Finance'),
    ('HISTORY', 'HISTORY'),
    ('Hotel Management', 'Hotel Management'),
    ('Human Resource', 'Human Resource'),
    ('Humanities Arts', 'Humanities Arts'),
    ('Humanities/Arts', 'Humanities/Arts'),
    ('IB', 'IB'),
    ('Income tax', 'Income tax'),
    ('IT', 'IT'),
    ('Law', 'Law'),
    ('Machanical', 'Machanical'),
    ('Marketing', 'Marketing'),
    ('Mass Communication', 'Mass Communication'),
    ('Mathematics', 'Mathematics'),
    ('Mechanical Engineering(Automobile)', 'Mechanical Engineering(Automobile)'),
    ('MECHENICAL', 'MECHENICAL'),
    ('Media & Mass Communication', 'Media & Mass Communication'),
    ('Music', 'Music'),
    ('Nursing', 'Nursing'),
    ('Physical Education', 'Physical Education'),
    ('Physical Science', 'Physical Science'),
    ('POLYTECHNIC', 'POLYTECHNIC'),
    ('sanskrit', 'sanskrit'),
    ('Science', 'Science'),
    ('VOCATIONAL', 'VOCATIONAL'),
    ('ZOLOGY', 'ZOLOGY'),
    ('OTHER', 'OTHER')
)

BOARDUNIVERSITY = (
    ('abc', 'abc'),
	('Acharya Nagarjuna University', 'Acharya Nagarjuna University'),
	('Adikavi Nannaya University', 'Adikavi Nannaya University'),
	('GRA UNIVERSHITY', 'GRA UNIVERSHITY'),
	('Ahmedabad University', 'Ahmedabad University'),
	('AHSEC', 'AHSEC'),
	('AJMER BOARD', 'AJMER BOARD'),
	('AKTU', 'AKTU'),
	('Alagappa University', 'Alagappa University'),
    ('Aliah University', 'Aliah University'),
    ('Aligarh Muslim University', 'Aligarh Muslim University'),
    ('All India Institute of Medical Sciences', 'All India Institute of Medical Sciences'),
    ('Alliance University', 'Alliance University'),
    ('AMALA INSTITUTE OF TECHNOLOGY &amp; MANAGEMENT', 'AMALA INSTITUTE OF TECHNOLOGY &amp; MANAGEMENT'),
    ('Amity University', 'Amity University'),
    ('AMRAVATI', 'AMRAVATI'),
    ('Amrita Vishwa Vidyapeetham', 'Amrita Vishwa Vidyapeetham'),
    ('AMU', 'AMU'),
    ('Anand Agricultural University', 'Anand Agricultural University'),
    ('Andhra Pradesh Board of Intermediate Education', 'Andhra Pradesh Board of Intermediate Education'),
    ('Andhra Pradesh Board of Secondary Education', 'Andhra Pradesh Board of Secondary Education'),
    ('Andhra University', 'Andhra University'),
    ('Anna University', 'Anna University'),
    ('Annamalai University', 'Annamalai University'),
    ('Apeejay Stya University', 'Apeejay Stya University'),
    ('Arni University', 'Arni University'),
    ('Aryabhatta Knowledge University', 'Aryabhatta Knowledge University'),
    ('Assam Agricultural University', 'Assam Agricultural University'),
    ('ASSAM BOARD', 'ASSAM BOARD'),
    ('Assam Don Bosco University', 'Assam Don Bosco University'),
    ('Assam Higher Secondary Education Council', 'Assam Higher Secondary Education Council'),
    ('Assam University', 'Assam University'),
    ('Avinashilingam University', 'Avinashilingam University'),
    ('Awadhesh Pratap Singh University', 'Awadhesh Pratap Singh University'),
    ('Ayush and Health Sciences University of Chhattisgarh', 'Ayush and Health Sciences University of Chhattisgarh'),
    ('Azim Premji University', 'Azim Premji University'),
    ('B I E UP BOAD', 'B I E UP BOAD'),
    ('B.R. Ambedkar Bihar University', 'B.R. Ambedkar Bihar University'),
    ('B.S. Abdur Rahman University', 'B.S. Abdur Rahman University'),
    ('Baba Farid University of Health Sciences', 'Baba Farid University of Health Sciences'),
    ('Baba Ghulam Shah Badhshah University', 'Baba Ghulam Shah Badhshah University'),
    ('Babasaheb Bhimrao Ambedkar University', 'Babasaheb Bhimrao Ambedkar University'),
    ('Babu Banarasi Das University', 'Babu Banarasi Das University'),
    ('Baddi University of Emerging Sciences and Technologies', 'Baddi University of Emerging Sciences and Technologies'),
    ('BAHRA University', 'BAHRA University'),
    ('Banaras Hindu University', 'Banaras Hindu University'),
    ('Banasthali Vidyapith', 'Banasthali Vidyapith'),
    ('Bangalore University', 'Bangalore University'),
    ('BAREILLY UNIVERSITY', 'BAREILLY UNIVERSITY'),
    ('Barkatullah University', 'Barkatullah University'),
    ('Bastar Vishwavidyalaya', 'Bastar Vishwavidyalaya'),
    ('BATAGARAWA', 'BATAGARAWA'),
    ('Bengal Engineering and Science University', 'Bengal Engineering and Science University'),
    ('Berhampur University', 'Berhampur University'),
    ('Bhagat Phool Singh Mahila Vishwavidyalaya', 'Bhagat Phool Singh Mahila Vishwavidyalaya'),
    ('Bhagwant University', 'Bhagwant University'),
    ('Bharat Ratna Dr. B.R. Ambedkar University', 'Bharat Ratna Dr. B.R. Ambedkar University'),
    ('Bharathiar University', 'Bharathiar University'),
    ('Bharathidasan University', 'Bharathidasan University'),
    ('Bharati Vidyapeeth University', 'Bharati Vidyapeeth University'),
    ('Bhatkhande Music Institute', 'Bhatkhande Music Institute'),
    ('BHSE', 'BHSE'),
    ('Bhupendra Narayan Mandal University', 'Bhupendra Narayan Mandal University'),
    ('Bidhan Chandra Krishi Vishwavidyalaya', 'Bidhan Chandra Krishi Vishwavidyalaya'),
    ('Bihar School Examination Board', 'Bihar School Examination Board'),
    ('Bihar State Madrasa Education Board', 'Bihar State Madrasa Education Board'),
    ('Biju Patnaik University of Technology', 'Biju Patnaik University of Technology'),
    ('Birla Institute of Technology', 'Birla Institute of Technology'),
    ('Birla Institute of Technology and Science', 'Birla Institute of Technology and Science'),
    ('Birsa Agricultural University', 'Birsa Agricultural University'),
    ('BNMU', 'BNMU'),
    ('Board of Higher Secondary Education, Delhi', 'Board of Higher Secondary Education, Delhi'),
    ('Board of Higher Secondary Education, Kerala', 'Board of Higher Secondary Education, Kerala'),
    ('Board of Intermediate Education Andhra Pradesh', 'Board of Intermediate Education Andhra Pradesh'),
    ('BOARD OF PUBLIC EXAMINATION', 'BOARD OF PUBLIC EXAMINATION'),
    ('BOARD OF SCHOOL EDUCATION UTTRAKHAND', 'BOARD OF SCHOOL EDUCATION UTTRAKHAND'),
    ('BOARD OF SCHOOL EDUCATION UTTRAKHNAD', 'BOARD OF SCHOOL EDUCATION UTTRAKHNAD'),
    ('Board of secondary &amp; Higher Education, UP', 'Board of secondary &amp; Higher Education, UP'),
    ('Board of secondary Education Andhra Pradesh', 'Board of secondary Education Andhra Pradesh'),
    ('Board of Secondary Education Kant Shahjahanpur Uttar Pradesh', 'Board of Secondary Education Kant Shahjahanpur Uttar Pradesh'),
    ('Board of Secondary Education, Assam', 'Board of Secondary Education, Assam'),
    ('Board of Secondary Education, Madhya Pradesh', 'Board of Secondary Education, Madhya Pradesh'),
    ('Board of Secondary Education, Orrisa', 'Board of Secondary Education, Orrisa'),
    ('Board of Secondary Education, Rajasthan', 'Board of Secondary Education, Rajasthan'),
    ('BOARD OF TECHNICAL EDU LUCKNOW', 'BOARD OF TECHNICAL EDU LUCKNOW'),
    ('Board of Technical Education', 'Board of Technical Education'),
    ('Board of Technical Eduction, U.P', 'Board of Technical Eduction, U.P'),
    ('BOARD OF TECHNICAL UNIVERSITY', 'BOARD OF TECHNICAL UNIVERSITY'),
    ('Board of Techniccal Education Delhi', 'Board of Techniccal Education Delhi'),
    ('Borad of School Examinations, Haryana', 'Borad of School Examinations, Haryana'),
    ('BS BOARD', 'BS BOARD'),
    ('BSE', 'BSE'),
    ('BTEUP', 'BTEUP'),
    ('BUNDELKHAND UNIVERSITY', 'BUNDELKHAND UNIVERSITY'),
    ("Calorx Teachers' University", "Calorx Teachers' University"),
    ('CENTARL INSTITUTE OF PLASTIC ENGENEERING', 'CENTARL INSTITUTE OF PLASTIC ENGENEERING'),
    ('Central Agricultural University', 'Central Agricultural University'),
    ('CENTRAL BOARD OF EDUCATION', 'CENTRAL BOARD OF EDUCATION'),
    ('Central Board of Secondary Education', 'Central Board of Secondary Education'),
    ('Central Institute of Fisheries Education', 'Central Institute of Fisheries Education'),
    ('Central University of Bihar', 'Central University of Bihar'),
    ('Central University of Gujarat', 'Central University of Gujarat'),
    ('Central University of Haryana', 'Central University of Haryana'),
    ('Central University of Himachal Pradesh', 'Central University of Himachal Pradesh'),
    ('Central University of Jharkhand' ,'Central University of Jharkhand'),
    ('Central University of Karnataka', 'Central University of Karnataka'),
    ('Central University of Kashmir', 'Central University of Kashmir'),
    ('Central University of Kerala', 'Central University of Kerala'),
    ('Central University of Orissa', 'Central University of Orissa'),
    ('Central University of Punjab', 'Central University of Punjab'),
    ('Central University of Rajasthan', 'Central University of Rajasthan'),
    ('Central University of Tamil Nadu', 'Central University of Tamil Nadu'),
    ('Central University of Tibetan Studies', 'Central University of Tibetan Studies'),
    ('Centurion University of Technology and Management', 'Centurion University of Technology and Management'),
    ('CEPT University', 'CEPT University'),
    ('Chanakya National Law University', 'Chanakya National Law University'),
    ('CHANDIGARH', 'CHANDIGARH'),
    ('Chandra Shekhar Azad University of Agriculture &amp; Technology', 'Chandra Shekhar Azad University of Agriculture &amp; Technology'),
    ('Charotar University of Science &amp; Technology', 'Charotar University of Science &amp; Technology'),
    ('Chaudhary Charan Singh Haryana Agricultural University', 'Chaudhary Charan Singh Haryana Agricultural University'),
    ('Chaudhary Charan Singh University', 'Chaudhary Charan Singh University'),
    ('Chaudhary Devi Lal University', 'Chaudhary Devi Lal University'),
    ('Chennai Mathematical Institute', 'Chennai Mathematical Institute'),
    ('CHETRAM SINGH MAHA VIDHALYA KASGANJ', 'CHETRAM SINGH MAHA VIDHALYA KASGANJ'),
    ('Chhatrapati Shahu Ji Maharaj University', 'Chhatrapati Shahu Ji Maharaj University'),
    ('Chhatrapati Shahuji Maharaj Medical University', 'Chhatrapati Shahuji Maharaj Medical University'),
    ('Chhattisgarh Board of Secondary Education', 'Chhattisgarh Board of Secondary Education'),
    ('Chhattisgarh Swami Vivekananda Technical University', 'Chhattisgarh Swami Vivekananda Technical University'),
    ('Chitkara University', 'Chitkara University'),
    ('Cochin University of Science and Technology', 'Cochin University of Science and Technology'),
    ('Council for the Indian School Certificate Examinations', 'Council for the Indian School Certificate Examinations'),
    ('Council of Higher Secondary Education, Orrisa', 'Council of Higher Secondary Education, Orrisa'),
    ('COUNCIL OF HIGHER SECONDRY EDUCATION ORRISSA', 'COUNCIL OF HIGHER SECONDRY EDUCATION ORRISSA'),
    ('Council of Secondary Education Mohali', 'Council of Secondary Education Mohali'),
    ('CSK Himachal Pradesh Agricultural University', 'CSK Himachal Pradesh Agricultural University'),
    ('D.U', 'D.U'),
    ('Damodaram Sanjivayya National Law University', 'Damodaram Sanjivayya National Law University'),
    ('Datta Meghe Institute of Medical Sciences', 'Datta Meghe Institute of Medical Sciences'),
    ('Davangere University', 'Davangere University'),
    ('Dayalbagh Educational Institute', 'Dayalbagh Educational Institute'),
    ('DBSIE', 'DBSIE'),
    ('Deccan College Post-Graduate and Research Institute', 'Deccan College Post-Graduate and Research Institute'),
    ('Deen Dayal Upadhyay Gorakhpur University', 'Deen Dayal Upadhyay Gorakhpur University'),
    ('Deenbandhu Chhotu Ram University of Science and Technology', 'Deenbandhu Chhotu Ram University of Science and Technology'),
    ('DELHI BOARD', 'DELHI BOARD'),
    ('Delhi Technological University', 'Delhi Technological University'),
    ('Department of Government Examination , Chennai', 'Department of Government Examination , Chennai'),
    ('DEPARTMENT OF GOVERNMENT EXAMINATION MADRAS', 'DEPARTMENT OF GOVERNMENT EXAMINATION MADRAS'),
    ('Department of Technical Education', 'Department of Technical Education'),
    ('Dev Sanskriti Vishwavidyalaya', 'Dev Sanskriti Vishwavidyalaya'),
    ('Devi Ahilya Vishwavidyalaya', 'Devi Ahilya Vishwavidyalaya'),
    ('Dharmsinh Desai University', 'Dharmsinh Desai University'),
    ('Dhirubhai Ambani Institute of Information &amp; Communication Technology', 'Dhirubhai Ambani Institute of Information &amp; Communication Technology'),
    ('Dibrugarh University', 'Dibrugarh University'),
    ('DON BOSCO INSTITUTE OF TECHNICAL EDUCATION', 'DON BOSCO INSTITUTE OF TECHNICAL EDUCATION'),
    ('Doon University', 'Doon University'),
    ('DOTE', 'DOTE'),
    ('Dr K.N. Modi University', 'Dr K.N. Modi University'),
    ('DR RAM MANOHAR LOHIA AWAD UNIVERSITY', 'DR RAM MANOHAR LOHIA AWAD UNIVERSITY'),
    ('DR. A P J  ABDUL KALAM TECHNICAL UNIVERSITY', 'DR. A P J  ABDUL KALAM TECHNICAL UNIVERSITY'),
    ('Dr. B R Ambedkar National Institute of Technology Jalandhar', 'Dr. B R Ambedkar National Institute of Technology Jalandhar'),
    ('Dr. B.R. Ambedkar University', 'Dr. B.R. Ambedkar University'),
    ('Dr. Babasaheb Ambedkar Marathwada University', 'Dr. Babasaheb Ambedkar Marathwada University'),
    ('Dr. Babasaheb Ambedkar Technological University', 'Dr. Babasaheb Ambedkar Technological University'),
    ('Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth', 'Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth'),
    ('Dr. C.V. Raman University', 'Dr. C.V. Raman University'),
    ('Dr. Hari Singh Gour University', 'Dr. Hari Singh Gour University'),
    ('Dr. Panjabrao Deshmukh Krishi Vidyapeeth', 'Dr. Panjabrao Deshmukh Krishi Vidyapeeth'),
    ('Dr. Ram Manohar Lohia Avadh University', 'Dr. Ram Manohar Lohia Avadh University'),
    ('Dr. Ram Manohar Lohiya National Law University', 'Dr. Ram Manohar Lohiya National Law University'),
    ('Dr. Shakuntala Misra Rehabilitation University', 'Dr. Shakuntala Misra Rehabilitation University'),
    ('Dr. Y.S. Parmar University of Horticulture and Forestry', 'Dr. Y.S. Parmar University of Horticulture and Forestry'),
    ('Dravidian University', 'Dravidian University'),
    ('DSSE', 'DSSE'),
    ('EIILM University', 'EIILM University'),
    ('Eternal University', 'Eternal University'),
    ('FAIZABAD UNIVERSITY', 'FAIZABAD UNIVERSITY'),
    ('Fakir Mohan University', 'Fakir Mohan University'),
    ('G.T.U', 'G.T.U'),
    ('Galgotias University', 'Galgotias University'),
    ('Gandhi Institute of Technology and Management', 'Gandhi Institute of Technology and Management'),
    ('Gandhigram Rural University', 'Gandhigram Rural University'),
    ('Ganpat University', 'Ganpat University'),
    ('Gauhati University', 'Gauhati University'),
    ('Gautam Buddh Technical University', 'Gautam Buddh Technical University'),
    ('Gautam Buddha University', 'Gautam Buddha University'),
    ('GLA University', 'GLA University'),
    ('Goa Board of Secondary &amp; Higher Secondary Education', 'Goa Board of Secondary &amp; Higher Secondary Education'),
    ('Goa University', 'Goa University'),
    ('Gokhale Institute of Politics and Economics', 'Gokhale Institute of Politics and Economics'),
    ('GOVERNMENT OF KERALA', 'GOVERNMENT OF KERALA'),
    ('Government Of Nepal', 'Government Of Nepal'),
    ('GOVERNMENT OF NEPAL MINISTRY EDUCATION', 'GOVERNMENT OF NEPAL MINISTRY EDUCATION'),
    ('Govind Ballabh Pant University of Agriculture &amp; Technology', 'Govind Ballabh Pant University of Agriculture &amp; Technology'),
    ('GOVT POLTYICNIC GORAKHPUR', 'GOVT POLTYICNIC GORAKHPUR'),
    ('GOVT POLYTECHNIC BHRAMPURI', 'GOVT POLYTECHNIC BHRAMPURI'),
    ('Govt.Polytechnic', 'Govt.Polytechnic'),
    ('GSHSE BOARD', 'GSHSE BOARD'),
    ('GTBPI', 'GTBPI'),
    ('Gujarat Ayurved University', 'Gujarat Ayurved University'),
    ('Gujarat Forensic Sciences University', 'Gujarat Forensic Sciences University'),
    ('Gujarat National Law University', 'Gujarat National Law University'),
    ('Gujarat Secondary &amp; Higher Secondary Education Board,Gandhinagar', 'Gujarat Secondary &amp; Higher Secondary Education Board,Gandhinagar'),
    ('Gujarat Secondary Education Board', 'Gujarat Secondary Education Board'),
    ('Gujarat Technological University', 'Gujarat Technological University'),
    ('Gujarat University', 'Gujarat University'),
    ('Gujarat Vidyapith', 'Gujarat Vidyapith'),
    ('Gulbarga University', 'Gulbarga University'),
    ('Guru Angad Dev Veterinary and Animal Sciences University', 'Guru Angad Dev Veterinary and Animal Sciences University'),
    ('Guru Ghasidas Vishwavidyalaya', 'Guru Ghasidas Vishwavidyalaya'),
    ('Guru Gobind Singh Indraprastha University', 'Guru Gobind Singh Indraprastha University'),
    ('Guru Jambheshwar University of Science &amp; Technology', 'Guru Jambheshwar University of Science &amp; Technology'),
    ('Guru Nanak Dev University', 'Guru Nanak Dev University'),
    ('H.B.S.E', 'H.B.S.E'),
    ('Haryana Board of School Education', 'Haryana Board of School Education'),
    ('HARYANA STATE BOARD', 'HARYANA STATE BOARD'),
    ('Haryana State Board of Technical Education', 'Haryana State Board of Technical Education'),
    ('Hemchandracharya North Gujarat University', 'Hemchandracharya North Gujarat University'),
    ('Hemwati Nandan Bahuguna Garhwal University', 'Hemwati Nandan Bahuguna Garhwal University'),
    ('Hidayatullah National Law University', 'Hidayatullah National Law University'),
    ('Higher Secondary Education', 'Higher Secondary Education'),
    ('Higher Secondary Education Board, Delhi', 'Higher Secondary Education Board, Delhi'),
    ('Higher Secondary Education Council, Assa', 'Higher Secondary Education Council, Assa'),
    ('Higher Secondary Education Council, Assam', 'Higher Secondary Education Council, Assam'),
    ('Himachal Pradesh Board of School Education', 'Himachal Pradesh Board of School Education'),
    ('Himachal Pradesh University', 'Himachal Pradesh University'),
    ('Himgiri ZEE University', 'Himgiri ZEE University'),
    ('Hindustan University', 'Hindustan University'),
    ('Homi Bhabha National Institute', 'Homi Bhabha National Institute'),
    ('HSBTE', 'HSBTE'),
    ('HSC', 'HSC'),
    ('HSE', 'HSE'),
    ('I.C.S BOARD', 'I.C.S BOARD'),
    ('I.C.S.C BOARD', 'I.C.S.C BOARD'),
    ('IASE UNIVERSITY', 'IASE UNIVERSITY'),
    ('ICFAI University, Dehradun', 'ICFAI University, Dehradun'),
    ('ICFAI University, Jharkhand', 'ICFAI University, Jharkhand'),
    ('ICFAI University, Tripura', 'ICFAI University, Tripura'),
    ('ICSE', 'ICSE'),
    ('ICSE BOARD', 'ICSE BOARD'),
    ('IFHE Hyderabad', 'IFHE Hyderabad'),
    ('IFTM University', 'IFTM University'),
    ('IGNOU', 'IGNOU'),
    ('Indian Agricultural Research Institute', 'Indian Agricultural Research Institute'),
    ('Indian Board of School Education West Bengal', 'Indian Board of School Education West Bengal'),
    ('Indian Institute of Foreign Trade', 'Indian Institute of Foreign Trade'),
    ('Indian Institute of Information Technology Allahabad', 'Indian Institute of Information Technology Allahabad'),
    ('Indian Institute of Information Technology and Management Gwalior', 'Indian Institute of Information Technology and Management Gwalior'),
    ('Indian Institute of Information Technology, Design and Manufacturing', 'Indian Institute of Information Technology, Design and Manufacturing'),
    ('Indian Institute of Science', 'Indian Institute of Science'),
    ('Indian Institute of Space Science and Technology', 'Indian Institute of Space Science and Technology'),
    ('Indian Institute of Technology Bhubaneswar', 'Indian Institute of Technology Bhubaneswar'),
    ('Indian Institute of Technology Bombay', 'Indian Institute of Technology Bombay'),
    ('Indian Institute of Technology Delhi', 'Indian Institute of Technology Delhi'),
    ('Indian Institute of Technology Gandhinagar', 'Indian Institute of Technology Gandhinagar'),
    ('Indian Institute of Technology Guwahati', 'Indian Institute of Technology Guwahati'),
    ('Indian Institute of Technology Hyderabad', 'Indian Institute of Technology Hyderabad'),
    ('Indian Institute of Technology Indore', 'Indian Institute of Technology Indore'),
    ('Indian Institute of Technology Jodhpur', 'Indian Institute of Technology Jodhpur'),
    ('Indian Institute of Technology Kanpur', 'Indian Institute of Technology Kanpur'),
    ('Indian Institute of Technology Kharagpur', 'Indian Institute of Technology Kharagpur'),
    ('Indian Institute of Technology Madras', 'Indian Institute of Technology Madras'),
    ('Indian Institute of Technology Mandi', 'Indian Institute of Technology Mandi'),
    ('Indian Institute of Technology Patna', 'Indian Institute of Technology Patna'),
    ('Indian Institute of Technology Roorkee', 'Indian Institute of Technology Roorkee'),
    ('Indian Institute of Technology Ropar', 'Indian Institute of Technology Ropar'),
    ('Indian Maritime University', 'Indian Maritime University'),
    ('Indian School of Mines', 'Indian School of Mines'),
    ('Indian Statistical Institute', 'Indian Statistical Institute'),
    ('Indian Veterinary Research Institute', 'Indian Veterinary Research Institute'),
    ('Indira Gandhi Agricultural University', 'Indira Gandhi Agricultural University'),
    ('Indira Gandhi Institute of Development Research', 'Indira Gandhi Institute of Development Research'),
    ('Indira Gandhi National Tribal University', 'Indira Gandhi National Tribal University'),
    ('Indira Kala Sangit Vishwavidyalaya', 'Indira Kala Sangit Vishwavidyalaya'),
    ('Indraprastha Institute of Information Technology', 'Indraprastha Institute of Information Technology'),
    ('Indus International University', 'Indus International University'),
    ('Institute of Chemical Technology', 'Institute of Chemical Technology'),
    ('Integral University', 'Integral University'),
    ('INTEGRATED INDTITUTE OF EDUCATION TECHNOLOGY', 'INTEGRATED INDTITUTE OF EDUCATION TECHNOLOGY'),
    ('International Institute for Population Sciences', 'International Institute for Population Sciences'),
    ('International Institute of Information Technology Bangalore', 'International Institute of Information Technology Bangalore'),
    ('International Institute of Information Technology, Hyderabad', 'International Institute of Information Technology, Hyderabad'),
    ('Invertis University', 'Invertis University'),
    ('Islamic University of Science and Technology', 'Islamic University of Science and Technology'),
    ('J.A.C', 'J.A.C'),
    ('J.K. BUJRAL PUNJAB TECHNICAL UNIVERSITY', 'J.K. BUJRAL PUNJAB TECHNICAL UNIVERSITY'),
    ('Jadavpur University', 'Jadavpur University'),
    ('JAG', 'JAG'),
    ('Jagadguru Ramanandacharya Rajasthan Sanskrit University', 'Jagadguru Ramanandacharya Rajasthan Sanskrit University'),
    ('Jagan Nath University', 'Jagan Nath University'),
    ('Jagdishprasad Jhabarmal Tibrewala University', 'Jagdishprasad Jhabarmal Tibrewala University'),
    ('Jai Narain Vyas University', 'Jai Narain Vyas University'),
    ('Jai Prakash Vishwavidyalaya', 'Jai Prakash Vishwavidyalaya'),
    ('Jain Vishva Bharati University', 'Jain Vishva Bharati University'),
    ('Jaipur National University', 'Jaipur National University'),
    ('Jamia Hamdard', 'Jamia Hamdard'),
    ('Jamia Millia Islamia', 'Jamia Millia Islamia'),
    ('Jammu &amp; Kashmir State Board of Technical Education', 'Jammu &amp; Kashmir State Board of Technical Education'),
    ('Jammu and Kashmir State Board of School Education', 'Jammu and Kashmir State Board of School Education'),
    ('Jawaharlal Institute of Postgraduate Medical Education &amp; Research', 'Jawaharlal Institute of Postgraduate Medical Education &amp; Research'),
    ('Jawaharlal Nehru Architecture and Fine Arts University', 'Jawaharlal Nehru Architecture and Fine Arts University'),
    ('Jawaharlal Nehru Centre for Advanced Scientific Research', 'Jawaharlal Nehru Centre for Advanced Scientific Research'),
    ('Jawaharlal Nehru Krishi Vishwavidyalaya', 'Jawaharlal Nehru Krishi Vishwavidyalaya'),
    ('Jawaharlal Nehru Technological University', 'Jawaharlal Nehru Technological University'),
    ('Jawaharlal Nehru Technological University, Anantapur', 'Jawaharlal Nehru Technological University, Anantapur'),
    ('Jawaharlal Nehru Technological University, Kakinada', 'Jawaharlal Nehru Technological University, Kakinada'),
    ('Jawaharlal Nehru University', 'Jawaharlal Nehru University'),
    ("Jayoti Vidyapeeth Women's University", "Jayoti Vidyapeeth Women's University"),
    ('Jaypee University of Engineering &amp; Technology', 'Jaypee University of Engineering &amp; Technology'),
    ('Jaypee University of Information Technology', 'Jaypee University of Information Technology'),
    ('JHARKHAND ACADEMIC COUNCIL', 'JHARKHAND ACADEMIC COUNCIL'),
    ('JHARKHAND ACADEMIC COUNCIL RANCHI', 'JHARKHAND ACADEMIC COUNCIL RANCHI'),
    ('JHARKHAND BOARD', 'JHARKHAND BOARD'),
    ('Jiwaji University', 'Jiwaji University'),
    ('Jodhpur National University', 'Jodhpur National University'),
    ('JSS University', 'JSS University'),
    ('Junagadh Agricultural University', 'Junagadh Agricultural University'),
    ('K L University', 'K L University'),
    ('Kadi Sarva VishwaVidyalaya', 'Kadi Sarva VishwaVidyalaya'),
    ('Kakatiya University', 'Kakatiya University'),
    ('KALASALINGAM UNIVERSITY', 'KALASALINGAM UNIVERSITY'),
    ('Kameshwar Singh Darbhanga Sanskrit University', 'Kameshwar Singh Darbhanga Sanskrit University'),
    ('Kannada University', 'Kannada University'),
    ('Kannur University', 'Kannur University'),
    ('Karnatak University', 'Karnatak University'),
    ('Karnataka Secondary Education Examination Board', 'Karnataka Secondary Education Examination Board'),
    ('Karnataka State Law University', 'Karnataka State Law University'),
    ("Karnataka State Women's University", "Karnataka State Women's University"),
    ('Karnataka Veterinary, Animal and Fisheries Sciences University', 'Karnataka Veterinary, Animal and Fisheries Sciences University'),
    ('Karunya University', 'Karunya University'),
    ('Kerala Agricultural University', 'Kerala Agricultural University'),
    ('Kerala Higher Secondary Examination Board', 'Kerala Higher Secondary Examination Board'),
    ('Kerala Kalamandalam', 'Kerala Kalamandalam'),
    ('Kerala University of Fisheries and Ocean Studies', 'Kerala University of Fisheries and Ocean Studies'),
    ('Kerala University of Health Sciences', 'Kerala University of Health Sciences'),
    ('Kerala Veterinary and Animal Sciences University', 'Kerala Veterinary and Animal Sciences University'),
    ('KIIT University', 'KIIT University'),
    ('KLE University', 'KLE University'),
    ('Kolhan University', 'Kolhan University'),
    ('Krantiguru Shyamji Krishna Verma Kachchh University', 'Krantiguru Shyamji Krishna Verma Kachchh University'),
    ('Krishna University', 'Krishna University'),
    ('KUK', 'KUK'),
    ('Kumaun University', 'Kumaun University'),
    ('KURUKSHETRA UNIVERSITY', 'KURUKSHETRA UNIVERSITY'),
    ('Kushabhau Thakre Patrakarita Avam Jansanchar University', 'Kushabhau Thakre Patrakarita Avam Jansanchar University'),
    ('Kuvempu University', 'Kuvempu University'),
    ('Lakshmibai National Institute of Physical Education', 'Lakshmibai National Institute of Physical Education'),
    ('Lalit Narayan Mithila University', 'Lalit Narayan Mithila University'),
    ('Lovely Professional University', 'Lovely Professional University'),
    ('LPU', 'LPU'),
    ('M.M PEG COLLAGE MODI NAGAR', 'M.M PEG COLLAGE MODI NAGAR'),
    ('M.P.B.S.E', 'M.P.B.S.E'),
    ('MADHAV UNIVERSITY', 'MADHAV UNIVERSITY'),
    ('MADHYA PRADESH BHOJ (OPEN) UNIVERSITY , BHOPAL', 'MADHYA PRADESH BHOJ (OPEN) UNIVERSITY , BHOPAL'),
    ('Madhya Pradesh Pashu-Chikitsa Vigyan Vishwavidyalaya', 'Madhya Pradesh Pashu-Chikitsa Vigyan Vishwavidyalaya'),
    ('Madurai Kamaraj University', 'Madurai Kamaraj University'),
    ('Magadh University', 'Magadh University'),
    ('Maharaja Ganga Singh University', 'Maharaja Ganga Singh University'),
    ('Maharaja Krishnakumarsinhji Bhavnagar University', 'Maharaja Krishnakumarsinhji Bhavnagar University'),
    ('Maharana Pratap University of Agriculture and Technology', 'Maharana Pratap University of Agriculture and Technology'),
    ('Maharashtra Animal and Fishery Sciences University', 'Maharashtra Animal and Fishery Sciences University'),
    ('Maharashtra State Board of Secondary and Higher Secondary Education', 'Maharashtra State Board of Secondary and Higher Secondary Education'),
    ('Maharashtra State Board of Technical Education', 'Maharashtra State Board of Technical Education'),
    ('Maharashtra University of Health Sciences', 'Maharashtra University of Health Sciences'),
    ('Maharishi Dayanand University', 'Maharishi Dayanand University'),
    ('Maharishi Mahesh Yogi Vedic Vishwavidyalaya', 'Maharishi Mahesh Yogi Vedic Vishwavidyalaya'),
    ('Maharishi University of Management and Technology', 'Maharishi University of Management and Technology'),
    ('Maharshi Dayanand Saraswati University', 'Maharshi Dayanand Saraswati University'),
    ('Maharshi Panini Sanskrit Vishwavidyalaya', 'Maharshi Panini Sanskrit Vishwavidyalaya'),
    ('Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya', 'Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya'),
    ('Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya', 'Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya'),
    ('Mahatma Gandhi Kashi Vidyapeeth', 'Mahatma Gandhi Kashi Vidyapeeth'),
    ('Mahatma Gandhi University', 'Mahatma Gandhi University'),
    ('Mahatma Jyoti Rao Phoole University', 'Mahatma Jyoti Rao Phoole University'),
    ('Mahatma Jyotiba Phule Rohilkhand University', 'Mahatma Jyotiba Phule Rohilkhand University'),
    ('Mahatma Phule Krishi Vidyapeeth', 'Mahatma Phule Krishi Vidyapeeth'),
    ('MAHOBA', 'MAHOBA'),
    ('Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya', 'Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya'),
    ('Malaviya National Institute of Technology, Jaipur', 'Malaviya National Institute of Technology, Jaipur'),
    ('Manav Bharti University', 'Manav Bharti University'),
    ('Mangalayatan University', 'Mangalayatan University'),
    ('Mangalore University', 'Mangalore University'),
    ('Manipal University', 'Manipal University'),
    ('Manipur University', 'Manipur University'),
    ('Manonmaniam Sundaranar University', 'Manonmaniam Sundaranar University'),
    ('Marathwada Agricultural University', 'Marathwada Agricultural University'),
    ('Martin Luther Christian University', 'Martin Luther Christian University'),
    ('MATS University', 'MATS University'),
    ('Maulana Abul Kalam Azad University of Technology', 'Maulana Abul Kalam Azad University of Technology'),
    ('Maulana Azad National Institute of Technology', 'Maulana Azad National Institute of Technology'),
    ('Maulana Azad National Urdu University', 'Maulana Azad National Urdu University'),
    ('Maulana Mazharul Haque Arabic and Persian University', 'Maulana Mazharul Haque Arabic and Persian University'),
    ('MBOSE', 'MBOSE'),
    ('Meghalaya Board of School Education', 'Meghalaya Board of School Education'),
    ('Mewar University', 'Mewar University'),
    ('MGM Institute of Health Sciences', 'MGM Institute of Health Sciences'),
    ('Mizoram Board of School Education', 'Mizoram Board of School Education'),
    ('Mizoram University', 'Mizoram University'),
    ('MJPRU', 'MJPRU'),
    ('MMS GOVT GIRLS POLYTRECHNIC MEERUT', 'MMS GOVT GIRLS POLYTRECHNIC MEERUT'),
    ('Mohammad Ali Jauhar University', 'Mohammad Ali Jauhar University'),
    ('Mohanlal Sukhadia University', 'Mohanlal Sukhadia University'),
    ('MONAD UNIVERSITY', 'MONAD UNIVERSITY'),
    ("Mother Teresa Women's University", "Mother Teresa Women's University"),
    ('Motilal Nehru National Institute of Technology', 'Motilal Nehru National Institute of Technology'),
    ('MUMBAI UNIVERSITY', 'MUMBAI UNIVERSITY'),
    ('Nagaland Board of School Education', 'Nagaland Board of School Education'),
    ('Nagaland University', 'Nagaland University'),
    ('NAGPUR', 'NAGPUR'),
    ('NAGPUR BOARD', 'NAGPUR BOARD'),
    ('NALSAR University of Law', 'NALSAR University of Law'),
    ('Narendra Dev University of Agriculture and Technology', 'Narendra Dev University of Agriculture and Technology'),
    ('Narsee Monjee Institute of Management and Higher Studies', 'Narsee Monjee Institute of Management and Higher Studies'),
    ('National Dairy Research Institute', 'National Dairy Research Institute'),
    ('NATIONAL INSTITIUTE OF OPEN SCHOOLING', 'NATIONAL INSTITIUTE OF OPEN SCHOOLING'),
    ('NATIONAL INSTITUDE OF OPEN', 'NATIONAL INSTITUDE OF OPEN'),
    ('NATIONAL INSTITUDE OF OPEN SCHOOLING', 'NATIONAL INSTITUDE OF OPEN SCHOOLING'),
    ('National Institute of Design', 'National Institute of Design'),
    ('National Institute of Fashion Technology', 'National Institute of Fashion Technology'),
    ('National Institute of Mental Health and Neuro Sciences', 'National Institute of Mental Health and Neuro Sciences'),
    ('National Institute of Open Schooling', 'National Institute of Open Schooling'),
    ('National Institute of Pharmaceutical Education and Research', 'National Institute of Pharmaceutical Education and Research'),
    ('National Institute of Pharmaceutical Education and Research, Ahmedabad', 'National Institute of Pharmaceutical Education and Research, Ahmedabad'),
    ('National Institute of Pharmaceutical Education and Research, Guwahati', 'National Institute of Pharmaceutical Education and Research, Guwahati'),
    ('National Institute of Pharmaceutical Education and Research, Hajipur', 'National Institute of Pharmaceutical Education and Research, Hajipur'),
    ('National Institute of Pharmaceutical Education and Research, Hyderabad', 'National Institute of Pharmaceutical Education and Research, Hyderabad'),
    ('National Institute of Pharmaceutical Education and Research, Kolkata', 'National Institute of Pharmaceutical Education and Research, Kolkata'),
    ('National Institute of Pharmaceutical Education and Research, Rae Bareli', 'National Institute of Pharmaceutical Education and Research, Rae Bareli'),
    ('National Institute of Technology Calicut', 'National Institute of Technology Calicut'),
    ('National Institute of Technology Karnataka', 'National Institute of Technology Karnataka'),
    ('National Institute of Technology Raipur', 'National Institute of Technology Raipur'),
    ('National Institute of Technology, Agartala', 'National Institute of Technology, Agartala'),
    ('National Institute of Technology, Durgapur', 'National Institute of Technology, Durgapur'),
    ('National Institute of Technology, Hamirpur', 'National Institute of Technology, Hamirpur'),
    ('National Institute of Technology, Jamshedpur', 'National Institute of Technology, Jamshedpur'),
    ('National Institute of Technology, Kurukshetra', 'National Institute of Technology, Kurukshetra'),
    ('National Institute of Technology, Patna', 'National Institute of Technology, Patna'),
    ('National Institute of Technology, Rourkela', 'National Institute of Technology, Rourkela'),
    ('National Institute of Technology, Silchar', 'National Institute of Technology, Silchar'),
    ('National Institute of Technology, Srinagar', 'National Institute of Technology, Srinagar'),
    ('National Institute of Technology, Tiruchirappalli', 'National Institute of Technology, Tiruchirappalli'),
    ('National Institute of Technology, Warangal', 'National Institute of Technology, Warangal'),
    ('National Law Institute University', 'National Law Institute University'),
    ('National Law School of India University', 'National Law School of India University'),
    ('National Law University', 'National Law University'),
    ('National Law University, Jodhpur', 'National Law University, Jodhpur'),
    ('National Law University, Orissa', 'National Law University, Orissa'),
    ('National University of Educational Planning and Administration', 'National University of Educational Planning and Administration'),
    ('National University of Study and Research in Law', 'National University of Study and Research in Law'),
    ('Navsari Agricultural University', 'Navsari Agricultural University'),
    ('NCVT', 'NCVT'),
    ('NEPAL BOARD', 'NEPAL BOARD'),
    ('Netaji Subhas Institute of Technology', 'Netaji Subhas Institute of Technology'),
    ('Nilamber-Pitamber University', 'Nilamber-Pitamber University'),
    ('NIMS University', 'NIMS University'),
    ('NIOS', 'NIOS'),
    ('Nirma University of Science and Technology', 'Nirma University of Science and Technology'),
    ('NITTE University', 'NITTE University'),
    ("Nizam's Institute of Medical Sciences", "Nizam's Institute of Medical Sciences"),
    ('Noida International University', 'Noida International University'),
    ('North East National Board of School Education', 'North East National Board of School Education'),
    ('North Eastern Hill University', 'North Eastern Hill University'),
    ('North Eastern Regional Institute of Science and Technology', 'North Eastern Regional Institute of Science and Technology'),
    ('North Maharashtra University', 'North Maharashtra University'),
    ('NORTH ODISHA UNIVERSITY', 'NORTH ODISHA UNIVERSITY'),
    ('North Orissa University', 'North Orissa University'),
    ('NTR University of Health Sciences', 'NTR University of Health Sciences'),
    ('O.P. Jindal Global University', 'O.P. Jindal Global University'),
    ('OPEN SCHOOLING', 'OPEN SCHOOLING'),
    ('Orissa Board of Secondary Education', 'Orissa Board of Secondary Education'),
    ('Orissa Council of Higher Secondary Education', 'Orissa Council of Higher Secondary Education'),
    ('Orissa University of Agriculture and Technology', 'Orissa University of Agriculture and Technology'),
    ('Osmania University', 'Osmania University'),
    ('Pacific University', 'Pacific University'),
    ('Padmashree Dr. D.Y. Patil Vidyapith', 'Padmashree Dr. D.Y. Patil Vidyapith'),
    ('Palamuru University', 'Palamuru University'),
    ('PANCHKULA TECHNICAL BOARD', 'PANCHKULA TECHNICAL BOARD'),
    ('Pandit Deendayal Petroleum University', 'Pandit Deendayal Petroleum University'),
    ('Pandit Ravishankar Shukla University', 'Pandit Ravishankar Shukla University'),
    ('Panjab University', 'Panjab University'),
    ('Patna University', 'Patna University'),
	('PDPM Indian Institute of Information Technology, Design &amp; Manufacturing', 'PDPM Indian Institute of Information Technology, Design &amp; Manufacturing'),
	('PEC University of Technology', 'PEC University of Technology'),
	('Periyar Maniammai University', 'Periyar Maniammai University'),
	('Pondicherry University', 'Pondicherry University'),
	('Post Graduate Institute of Medical Education and Research', 'Post Graduate Institute of Medical Education and Research'),
	('Potti Sreeramulu Telugu University', 'Potti Sreeramulu Telugu University'),
	('Pravara Institute of Medical Sciences', 'Pravara Institute of Medical Sciences'),
	('Presidency University', 'Presidency University'),
	('Pt. B. D. Sharma University of Health Sciences', 'Pt. B. D. Sharma University of Health Sciences'),
	('PUC', 'PUC'),
	('PUNE', 'PUNE'),
	('Punjab Agricultural University', 'Punjab Agricultural University'),
	('Punjab School Education Board', 'Punjab School Education Board'),
	('Punjab Technical University', 'Punjab Technical University'),
	('Punjabi University', 'Punjabi University'),
	('Rabindra Bharati University', 'Rabindra Bharati University'),
	('Raffles University', 'Raffles University'),
	('Rajasthan Agricultural University', 'Rajasthan Agricultural University'),
	('Rajasthan Ayurved University', 'Rajasthan Ayurved University'),
	('RAJASTHAN BOARD', 'RAJASTHAN BOARD'),
	('Rajasthan Technical University Kota', 'Rajasthan Technical University Kota'),
	('Rajasthan University of Health Sciences', 'Rajasthan University of Health Sciences'),
	('Rajendra Agricultural University', 'Rajendra Agricultural University'),
	('Rajiv Gandhi National University of Law', 'Rajiv Gandhi National University of Law'),
	('Rajiv Gandhi Proudyogiki Vishwavidyalaya', 'Rajiv Gandhi Proudyogiki Vishwavidyalaya'),
	('Rajiv Gandhi University', 'Rajiv Gandhi University'),
	('Rajiv Gandhi University of Health Sciences', 'Rajiv Gandhi University of Health Sciences'),
	('RAJKIYA INSTITUDE OF OPEN SCHOOLING', 'RAJKIYA INSTITUDE OF OPEN SCHOOLING'),
	('RAM MANOHAR LOHIA AVADH UNIVERSITY', 'RAM MANOHAR LOHIA AVADH UNIVERSITY'),
	('Ramakrishna Mission Vivekananda University', 'Ramakrishna Mission Vivekananda University'),
	('RAMGAHUR SINGH MEMORIYAL DEGREE COLLAGE MALIK, RAMPUR', 'RAMGAHUR SINGH MEMORIYAL DEGREE COLLAGE MALIK, RAMPUR'),
	('Ranchi University', 'Ranchi University'),
	('Rani Channamma University', 'Rani Channamma University'),
	('Rani Durgavati Vishwavidyalaya', 'Rani Durgavati Vishwavidyalaya'),
	('Rashtrasant Tukadoji Maharaj Nagpur University', 'Rashtrasant Tukadoji Maharaj Nagpur University'),
	('Rashtriya Sanskrit Sansthan', 'Rashtriya Sanskrit Sansthan'),
	('Rashtriya Sanskrit Vidyapeetha', 'Rashtriya Sanskrit Vidyapeetha'),
	('Ravenshaw University', 'Ravenshaw University'),
	('Rayalaseema University', 'Rayalaseema University'),
	('RVU', 'RVU'),
	('S.B.S.E', 'S.B.S.E'),
	('S.E.B.A', 'S.E.B.A'),
	('Sam Higginbottom Institute of Agriculture, Technology and Sciences', 'Sam Higginbottom Institute of Agriculture, Technology and Sciences'),
	('Sambalpur University', 'Sambalpur University'),
	('Sampurnanand Sanskrit Vishvavidyalaya', 'Sampurnanand Sanskrit Vishvavidyalaya'),
	('Sanjay Gandhi Post Graduate Institute of Medical Sciences', 'Sanjay Gandhi Post Graduate Institute of Medical Sciences'),
	('Sant Gadge Baba Amravati University', 'Sant Gadge Baba Amravati University'),
	('Sant Longowal Institute of Engineering and Technology', 'Sant Longowal Institute of Engineering and Technology'),
	('Sardar Patel University', 'Sardar Patel University'),
	('Sardar Vallabhbhai National Institute of Technology, Surat', 'Sardar Vallabhbhai National Institute of Technology, Surat'),
	('Sardar Vallabhbhai Patel University of Agriculture and Technology', 'Sardar Vallabhbhai Patel University of Agriculture and Technology'),
	('Sardarkrushinagar Dantiwada Agricultural University', 'Sardarkrushinagar Dantiwada Agricultural University'),
	('Sarguja University', 'Sarguja University'),
	('SASTRA University', 'SASTRA University'),
	('Satavahana University', 'Satavahana University'),
	('Sathyabama University', 'Sathyabama University'),
	('SATYAM FASHION UNIVERSITY', 'SATYAM FASHION UNIVERSITY'),
	('Saurashtra University', 'Saurashtra University'),
	('SAYTAM FASHION UNIVERSITY', 'SAYTAM FASHION UNIVERSITY'),
	('School of Planning and Architecture, Delhi', 'School of Planning and Architecture, Delhi'),
	('SEB', 'SEB'),
	('SEBA', 'SEBA'),
	('Sharda University', 'Sharda University'),
	('Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir', 'Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir'),
	('Shiv Nadar University', 'Shiv Nadar University'),
	('Shivaji University', 'Shivaji University'),
	('SHOBHIT UNIVERSITY MEERUT', 'SHOBHIT UNIVERSITY MEERUT'),
	('Shoolini University of Biotechnology and Management Sciences', 'Shoolini University of Biotechnology and Management Sciences'),
	('Shree Somnath Sanskrit University', 'Shree Somnath Sanskrit University'),
	("Shreemati Nathibai Damodar Thackersey Women's University", "Shreemati Nathibai Damodar Thackersey Women's University"),
	('Shri Guru Ram Rai Education Mission', 'Shri Guru Ram Rai Education Mission'),
	('Shri Jagannath Sanskrit Vishvavidyalaya', 'Shri Jagannath Sanskrit Vishvavidyalaya'),
	('Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha', 'Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha'),
	('Shri Mata Vaishno Devi University', 'Shri Mata Vaishno Devi University'),
	('Shri Venkateshwara University', 'Shri Venkateshwara University'),
	('Shridhar University', 'Shridhar University'),
	('Sidho Kanho Birsha University', 'Sidho Kanho Birsha University'),
	('Sido Kanhu Murmu University', 'Sido Kanhu Murmu University'),
	('Sikkim Manipal University', 'Sikkim Manipal University'),
	('Sikkim University', 'Sikkim University'),
	('Singhania University', 'Singhania University'),
	('Sir Padampat Singhania University', 'Sir Padampat Singhania University'),
	('South Asian University', 'South Asian University'),
	('Sree Chitra Thirunal Institute of Medical Sciences and Technology', 'Sree Chitra Thirunal Institute of Medical Sciences and Technology'),
	('Sree Sankaracharya University of Sanskrit', 'Sree Sankaracharya University of Sanskrit'),
	('Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya', 'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya'),
	('Sri Guru Granth Sahib World University', 'Sri Guru Granth Sahib World University'),
	('Sri Krishnadevaraya University', 'Sri Krishnadevaraya University'),
	('Sri Padmavati Mahila Visvavidyalayam', 'Sri Padmavati Mahila Visvavidyalayam'),
	('Sri Ramachandra University', 'Sri Ramachandra University'),
	('Sri Sai University', 'Sri Sai University'),
	('Sri Venkateswara Institute of Medical Sciences', 'Sri Venkateswara Institute of Medical Sciences'),
	('Sri Venkateswara University', 'Sri Venkateswara University'),
	('Sri Venkateswara Vedic University', 'Sri Venkateswara Vedic University'),
	('Sri Venkateswara Veterinary University', 'Sri Venkateswara Veterinary University'),
	('SRM University', 'SRM University'),
	('SSC BOARD', 'SSC BOARD'),
	('SSLC', 'SSLC'),
	('ST FWNIS TECH INSTITUT', 'ST FWNIS TECH INSTITUT'),
	('STATE BOARD OF SCHOOL EDUCATION', 'STATE BOARD OF SCHOOL EDUCATION'),
	('State Board of Technical Education and Training', 'State Board of Technical Education and Training'),
	('State Board of Technical Education, Jharkhand', 'State Board of Technical Education, Jharkhand'),
	('STATE COUNCIL FOR TECHNICAL EDUCATION &amp; VOCATIONAL TRAINING', 'STATE COUNCIL FOR TECHNICAL EDUCATION &amp; VOCATIONAL TRAINING'),
	('SUBHARTI UNIVERSITY', 'SUBHARTI UNIVERSITY'),
	('SunRise University', 'SunRise University'),
	('Suresh Gyan Vihar University', 'Suresh Gyan Vihar University'),
	('SURESH SEEP POLYTECHNIC', 'SURESH SEEP POLYTECHNIC'),
	('Swami Ramanand Teerth Marathwada University', 'Swami Ramanand Teerth Marathwada University'),
	('Swami Vivekanand Subharti University', 'Swami Vivekanand Subharti University'),
	('Symbiosis International University', 'Symbiosis International University'),
	('Tamil Nadu Agricultural University', 'Tamil Nadu Agricultural University'),
	('Tamil Nadu Board of Secondary Education', 'Tamil Nadu Board of Secondary Education'),
	('Tamil Nadu Dr Ambedkar Law University', 'Tamil Nadu Dr Ambedkar Law University'),
	('Tamil Nadu Dr. M.G.R.Medical University', 'Tamil Nadu Dr. M.G.R.Medical University'),
	('Tamil Nadu Physical Education and Sports University', 'Tamil Nadu Physical Education and Sports University'),
	('Tamil Nadu Teacher Education University', 'Tamil Nadu Teacher Education University'),
	('Tamil Nadu Veterinary and Animal Sciences University', 'Tamil Nadu Veterinary and Animal Sciences University'),
	('Tamil University', 'Tamil University'),
	('Tata Institute of Fundamental Research', 'Tata Institute of Fundamental Research'),
	('Tata Institute of Social Sciences', 'Tata Institute of Social Sciences'),
	('Teerthanker Mahaveer University', 'Teerthanker Mahaveer University'),
	('Telangana Board of Intermediate Education', 'Telangana Board of Intermediate Education'),
	('Telangana Board of Secondary Education', 'Telangana Board of Secondary Education'),
	('Telangana University', 'Telangana University'),
	('TERI University', 'TERI University'),
	('Tezpur University', 'Tezpur University'),
    ('Thapar University', 'Thapar University'),
    ('The English and Foreign Languages University', 'The English and Foreign Languages University'),
    ('The Indian Law Institute', 'The Indian Law Institute'),
    ('THE JAMMU &amp; KASHMIR STATE BOARD OF SCHOOL EDUCATION', 'THE JAMMU &amp; KASHMIR STATE BOARD OF SCHOOL EDUCATION'),
    ('The LNM Institute of Information Technology', 'The LNM Institute of Information Technology'),
    ('The Maharaja Sayajirao University of Baroda', 'The Maharaja Sayajirao University of Baroda'),
    ('The National University of Advanced Legal Studies', 'The National University of Advanced Legal Studies'),
    ('The Northcap University', 'The Northcap University'),
    ('The WB National University of Juridical Sciences', 'The WB National University of Juridical Sciences'),
    ('Thiruvalluvar University', 'Thiruvalluvar University'),
    ('Tilka Manjhi Bhagalpur University', 'Tilka Manjhi Bhagalpur University'),
    ('Tripura Board of Secondary Education', 'Tripura Board of Secondary Education'),
    ('Tripura University', 'Tripura University'),
    ('Tumkur University', 'Tumkur University'),
    ('Ucchatar Madhyamik Shiksha Mandal Delhi', 'Ucchatar Madhyamik Shiksha Mandal Delhi'),
    ('University of Agricultural Sciences, Bangalore', 'University of Agricultural Sciences, Bangalore'),
    ('University of Agricultural Sciences, Dharwad', 'University of Agricultural Sciences, Dharwad'),
    ('University of Allahabad', 'University of Allahabad'),
    ('University Of Bhopal', 'University Of Bhopal'),
    ('University of Burdwan', 'University of Burdwan'),
    ('University of Calcutta', 'University of Calcutta'),
    ('University of Calicut', 'University of Calicut'),
    ('University of Delhi', 'University of Delhi'),
    ('University of Gour Banga', 'University of Gour Banga'),
    ('University of Hyderabad', 'University of Hyderabad'),
    ('University of Jammu', 'University of Jammu'),
    ('University of Kalyani', 'University of Kalyani'),
    ('University of Kashmir', 'University of Kashmir'),
    ('University of Kerala', 'University of Kerala'),
    ('University of Kota', 'University of Kota'),
    ('University of Lucknow', 'University of Lucknow'),
    ('University of Madras', 'University of Madras'),
    ('University of Mumbai', 'University of Mumbai'),
    ('University of Mysore', 'University of Mysore'),
    ('University of North Bengal', 'University of North Bengal'),
    ('University of Petroleum and Energy Studies','University of Petroleum and Energy Studies'),
	('University of Pune', 'University of Pune'),
	('University of Rajasthan', 'University of Rajasthan'),
	('University of Solapur', 'University of Solapur'),
	('University of Technology &amp; Management', 'University of Technology &amp; Management'),
	('UP Board of Madarsha Education, Lucknow', 'UP Board of Madarsha Education, Lucknow'),
	('UPBTE', 'UPBTE'),
	('Utkal University', 'Utkal University'),
	('Uttar Banga Krishi Viswavidyalaya', 'Uttar Banga Krishi Viswavidyalaya'),
	('UTTAR PRADESH TECHNICAL EDUCATION', 'UTTAR PRADESH TECHNICAL EDUCATION'),
	('Uttar Pradesh Technical University', 'Uttar Pradesh Technical University'),
	('Uttarakhand Board of School Education', 'Uttarakhand Board of School Education'),
	('Uttarakhand Technical University', 'Uttarakhand Technical University'),
	('Uttaranchal Sanskrit University', 'Uttaranchal Sanskrit University'),
	('Uttaranchal University, Dehradun', 'Uttaranchal University, Dehradun'),
	('Utter Pradesh madhymik shiksha parishad allahabad', 'Utter Pradesh madhymik shiksha parishad allahabad'),
	('UTTRAKHAND TECHNICAL UNIVERSITY', 'UTTRAKHAND TECHNICAL UNIVERSITY'),
	('UTTRANCHAL', 'UTTRANCHAL'),
	('Veer Bahadur Singh Purvanchal University', 'Veer Bahadur Singh Purvanchal University'),
	('Veer Kunwar Singh University', 'Veer Kunwar Singh University'),
	('Veer Narmad South Gujarat University', 'Veer Narmad South Gujarat University'),
	('Veer Surendra Sai University of Technology', 'Veer Surendra Sai University of Technology'),
	('Vel Tech Dr.RR &amp; Dr.SR Technical University', 'Vel Tech Dr.RR &amp; Dr.SR Technical University'),
	('Vidyasagar University', 'Vidyasagar University'),
	('Vijayanagara Sri Krishnadevaraya University', 'Vijayanagara Sri Krishnadevaraya University'),
	('Vikram University', 'Vikram University'),
    ('Vikrama Simhapuri University', 'Vikrama Simhapuri University'),
    ('VIMT', 'VIMT'),
    ('Vinayaka Missions Sikkim University', 'Vinayaka Missions Sikkim University'),
    ('VINAYAKA MISSONS UNIVERSITY', 'VINAYAKA MISSONS UNIVERSITY'),
    ('Vinoba Bhave University', 'Vinoba Bhave University'),
    ('VIRGINIA BOARD', 'VIRGINIA BOARD'),
    ('Visva Bharati University', 'Visva Bharati University'),
    ('Visvesvaraya National Institute of Technology', 'Visvesvaraya National Institute of Technology'),
    ('Visvesvaraya Technological University', 'Visvesvaraya Technological University'),
    ('VIT University', 'VIT University'),
    ('West Bengal Board of Madrasah Education', 'West Bengal Board of Madrasah Education'),
    ('West Bengal Board of Primary Education', 'West Bengal Board of Primary Education'),
    ('West Bengal Board of Secondary Education', 'West Bengal Board of Secondary Education'),
	('West Bengal Council of Higher Secondary Education', 'West Bengal Council of Higher Secondary Education'),
	('West Bengal Council of Rabindra Open Schooling', ' West Bengal Council of Rabindra Open Schooling'),
	('West Bengal State Council of Technical Education', 'West Bengal State Council of Technical Education'),
	('West Bengal State Council of Vocational Education and Training', 'West Bengal State Council of Vocational Education and Training'),
	('West Bengal State University', 'West Bengal State University'),
	('West Bengal University of Animal and Fishery Sciences', 'West Bengal University of Animal and Fishery Sciences'),
	('West Bengal University of Health Sciences', 'West Bengal University of Health Sciences'),
	('Yashwantrao Chavan Maharashtra Open University', 'Yashwantrao Chavan Maharashtra Open University'),
	('YMCA University of Science and Technology', 'YMCA University of Science and Technology'),
	('Yogi Vemana University', 'Yogi Vemana University'),
)

class Profile(models.Model):
    name = models.CharField(max_length=255)
    gender = models.CharField(max_length=50, choices=GENDER)
    mothersName = models.CharField(max_length=255)
    fathersName = models.CharField(max_length=255)
    bloodGroup = models.CharField(choices=BLOOD, max_length=3)
    maritalStatus = models.CharField(choices=MARITAL, max_length=15)
    aadharCardNo = models.CharField(max_length=255)
    aadharFrontImg = models.ImageField()
    aadharBackImg = models.ImageField()
    yourPhoto = models.ImageField()
    yourCV = models.ImageField()
    primarylang = models.CharField(max_length=100, choices=LANGUAGE)
    secondarylang = models.CharField( max_length=100, choices=LANGUAGE)

class Education(models.Model):
    secondaryLevel = models.CharField(max_length=255)
    specialization = models.CharField(max_length=100, choices=SPECIALIZATION)
    board = models.CharField(max_length=100, choices=BOARDUNIVERSITY)


class Contact(models.Model):
    mobile = models.IntegerField()
    alternateMobile = models.IntegerField()
    emergencyMobile = models.IntegerField()
    relationWithEmergencyContact = models.IntegerField()
    email = models.EmailField()
    accept = models.BooleanField(default=False)
